import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useContext, useState } from 'react';
import { Link } from 'react-router-dom';
import { AuthContext } from '../context/AuthContext';
import LogoutButton from './LogoutButton';
import '../App.css';
const Header = () => {
    const { isAuthenticated } = useContext(AuthContext);
    const [menuOpen, setMenuOpen] = useState(false);
    const toggleMenu = () => setMenuOpen(!menuOpen);
    const closeMenu = () => setMenuOpen(false);
    return (_jsxs("header", { className: "bg-dark text-white shadow sticky-top", children: [_jsxs("div", { className: "container d-flex py-3 justify-content-between align-items-center", children: [_jsx("h1", { className: "m-0", children: "\uD83D\uDC3B Boozy Bears Hockey" }), _jsxs("button", { className: "custom-toggler d-lg-none border-1 bg-transparent", type: "button", "aria-label": "Toggle navigation", onClick: toggleMenu, children: [_jsx("div", { className: "toggler-icon" }), _jsx("div", { className: "toggler-icon" }), _jsx("div", { className: "toggler-icon" })] }), _jsx("nav", { className: "d-none d-lg-block", children: _jsxs("ul", { className: "nav", children: [_jsx("li", { className: "nav-item", children: _jsx(Link, { to: "/", className: "nav-link text-white", children: "\uD83C\uDFE0 Home" }) }), _jsx("li", { className: "nav-item", children: _jsx(Link, { to: "/roster", className: "nav-link text-white", children: "\uD83C\uDFD2 Players" }) }), _jsx("li", { className: "nav-item", children: _jsx(Link, { to: "/admin-dashboard", className: "nav-link text-white", children: "Admin" }) }), _jsx("li", { className: "nav-item", children: isAuthenticated ? (_jsx(LogoutButton, {})) : (_jsx(Link, { to: "/login", className: "btn btn-outline-light ms-2", children: "\uD83D\uDD10 Login" })) })] }) }), _jsx("div", { className: "ms-3 d-none d-lg-block", children: _jsx("span", { className: "badge bg-secondary", children: isAuthenticated ? '✅ LOGGED IN' : '❌ NOT LOGGED IN' }) })] }), menuOpen && (_jsx("div", { className: "bg-dark d-lg-none border-top border-bottom border-2 border-white", children: _jsxs("ul", { className: "nav flex-column text-center", children: [_jsx("li", { className: "nav-item", children: _jsx(Link, { to: "/", className: "nav-link text-white", onClick: closeMenu, children: "\uD83C\uDFE0 Home" }) }), _jsx("li", { className: "nav-item", children: _jsx(Link, { to: "/roster", className: "nav-link text-white", onClick: closeMenu, children: "\uD83C\uDFD2 Players" }) }), _jsx("li", { className: "nav-item", children: _jsx(Link, { to: "/admin-dashboard", className: "nav-link text-white", onClick: closeMenu, children: "Admin" }) }), isAuthenticated ? (_jsxs(_Fragment, { children: [_jsx("li", { className: "nav-item", children: _jsx("span", { className: "nav-link text-warning", children: "\u2705 Logged In" }) }), _jsx("li", { className: "nav-item", children: _jsx(LogoutButton, {}) })] })) : (_jsx("li", { className: "nav-item", id: "last-nav", children: _jsx(Link, { to: "/login", className: "nav-link text-white", onClick: closeMenu, children: "\uD83D\uDD10 Login" }) }))] }) }))] }));
};
export default Header;
